import{initializeApp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import{getFirestore,doc,getDoc,collection,onSnapshot,query,orderBy}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const cfg={apiKey:"AIzaSyAufmht7zvxG_8fwUeb59NBENppnt-MlhY",authDomain:"setor-de-fadiga.firebaseapp.com",projectId:"setor-de-fadiga",storageBucket:"setor-de-fadiga.firebasestorage.app",messagingSenderId:"843558361497",appId:"1:843558361497:web:54db0e57a70bcb0eb9db08"};
const fb=initializeApp(cfg),auth=getAuth(fb),db=getFirestore(fb),$=s=>document.querySelector(s);
let rel=[],pen=[],perfil=null;
const norm=s=>(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();
$("#entrar").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("#email").value.trim(),$("#senha").value)}catch(e){$("#loginMsg").textContent="Não foi possível entrar. Verifique e-mail e senha."}};
$("#sair").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u){$("#login").classList.remove("hidden");$("#app").classList.add("hidden");return}const s=await getDoc(doc(db,"usuarios",u.uid));if(!s.exists()||s.data().ativo!==true){await signOut(auth);return}perfil=s.data();if(!["administrador","gestor"].includes(perfil.perfil)){ $("#loginMsg").textContent="Este acesso é exclusivo da gestão.";await signOut(auth);return}$("#userBadge").textContent=`${perfil.nome||"Gestão"} • ${perfil.perfil}`;$("#login").classList.add("hidden");$("#app").classList.remove("hidden");escutar()});
function escutar(){onSnapshot(query(collection(db,"relatorios"),orderBy("createdAt","desc")),s=>{rel=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()});onSnapshot(collection(db,"pendencias"),s=>{pen=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()})}
document.querySelectorAll(".nav[data-page]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("on"));b.classList.add("on");document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$("#page-"+b.dataset.page).classList.add("active");renderAll()});
["#dIni","#dFim","#fTurno","#fResp","#rData","#rTurno","#rSit","#rBusca","#pStatus","#pBusca"].forEach(id=>$(id).addEventListener("input",renderAll));
$("#limpar").onclick=()=>{$("#dIni").value=$("#dFim").value=$("#fTurno").value=$("#fResp").value="";renderAll()};
function dashFilter(r){return(!$("#dIni").value||r.dataTurno>=$("#dIni").value)&&(!$("#dFim").value||r.dataTurno<=$("#dFim").value)&&(!$("#fTurno").value||r.turno==$("#fTurno").value)&&(!$("#fResp").value||r.responsavelNome==$("#fResp").value)}
function renderAll(){let a=rel.filter(dashFilter);$("#kRel").textContent=a.length;$("#kNor").textContent=a.filter(x=>norm(x.situacao)=="NORMAL").length;$("#kAte").textContent=a.filter(x=>norm(x.situacao)=="ATENCAO").length;$("#kOco").textContent=a.filter(x=>norm(x.situacao)=="OCORRENCIA").length;$("#kPen").textContent=pen.filter(x=>norm(x.status)=="ABERTA").length;
let vals=[["Normal",a.filter(x=>norm(x.situacao)=="NORMAL").length],["Atenção",a.filter(x=>norm(x.situacao)=="ATENCAO").length],["Ocorrência",a.filter(x=>norm(x.situacao)=="OCORRENCIA").length],["Total",a.length]],mx=Math.max(1,...vals.map(x=>x[1]));$("#bars").innerHTML=vals.map(x=>`<div class="barrow"><b>${x[0]}</b><div class="bar"><div class="fill" style="width:${x[1]/mx*100}%"></div></div><b>${x[1]}</b></div>`).join("");
$("#recentes").innerHTML=a.slice(0,5).map(cardRel).join("")||"<p>Nenhum relatório no filtro.</p>";renderRel();renderPen();bind()}
function cardRel(r){let s=norm(r.situacao),c=s=="OCORRENCIA"?"red":s=="NORMAL"?"green":"";return`<div class="item ${c}"><span class="tag ${c}">${s||"-"}</span><h3>${esc(r.responsavelNome)} • Turno ${esc(r.turno)}</h3><div class="meta">${dataBR(r.dataTurno)} • ${esc(r.horario)}</div><p>${esc(r.resumo||"Sem resumo")}</p><button class="action view" data-id="${r.id}">Visualizar completo</button></div>`}
function renderRel(){let q=norm($("#rBusca").value),a=rel.filter(r=>(!$("#rData").value||r.dataTurno==$("#rData").value)&&(!$("#rTurno").value||r.turno==$("#rTurno").value)&&(!$("#rSit").value||norm(r.situacao)==$("#rSit").value)&&(!q||norm(JSON.stringify(r)).includes(q)));$("#listaRel").innerHTML=a.map(cardRel).join("")||"<p>Nenhum relatório encontrado.</p>"}
function renderPen(){let q=norm($("#pBusca").value),a=pen.filter(p=>(!$("#pStatus").value||norm(p.status)==$("#pStatus").value)&&(!q||norm(JSON.stringify(p)).includes(q)));$("#listaPen").innerHTML=a.map(p=>`<div class="item"><span class="tag">${norm(p.status)}</span><h3>Pendência</h3><div class="meta">Origem: ${esc(p.openedByNome||"-")} • Turno ${esc(p.turnoOrigem||"-")}</div><p>${esc(p.descricao||"-")}</p></div>`).join("")||"<p>Nenhuma pendência encontrada.</p>"}
function bind(){document.querySelectorAll(".view").forEach(b=>b.onclick=()=>abrir(rel.find(x=>x.id==b.dataset.id)))}
function abrir(r){if(!r)return;$("#modalBody").innerHTML=`<div class="eyebrow">RELATÓRIO COMPLETO</div><h1>${esc(r.responsavelNome)} • Turno ${esc(r.turno)}</h1>${det("Data",dataBR(r.dataTurno))}${det("Horário",r.horario)}${det("Situação",r.situacao)}${det("Sistema de Fadiga",r.sistemaFadiga)}${det("Condições Operacionais",r.condicoesOperacionais)}${det("Resumo",r.resumo)}${det("Ocorrências",r.ocorrencias)}${det("Pendências recebidas",r.pendenciasRecebidas)}${det("Pendências geradas",r.pendenciasGeradas)}${det("Ações realizadas",r.acoes)}${det("Passagem de turno / Observações",r.passagemTurno)}`;$("#modal").classList.remove("hidden")}
$("#fechar").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target.id=="modal")$("#modal").classList.add("hidden")};
function det(a,b){return`<div class="detail"><b>${a}</b><br>${esc(b||"-")}</div>`}function dataBR(v){if(!v)return"-";let [y,m,d]=v.split("-");return`${d}/${m}/${y}`}function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}