import{initializeApp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import{getFirestore,doc,getDoc,collection,onSnapshot,query,orderBy,addDoc,updateDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const cfg={apiKey:"AIzaSyAufmht7zvxG_8fwUeb59NBENppnt-MlhY",authDomain:"setor-de-fadiga.firebaseapp.com",projectId:"setor-de-fadiga",storageBucket:"setor-de-fadiga.firebasestorage.app",messagingSenderId:"843558361497",appId:"1:843558361497:web:54db0e57a70bcb0eb9db08"};
const fb=initializeApp(cfg),auth=getAuth(fb),db=getFirestore(fb),$=s=>document.querySelector(s);let rel=[],pen=[],ciencias=[],perfil=null,user=null,relAtual=null;
const norm=s=>(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase(),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const dataBR=v=>{if(!v)return"-";let[y,m,d]=v.split("-");return`${d}/${m}/${y}`},tsBR=t=>{try{return t?.toDate().toLocaleString("pt-BR")||"-"}catch{return"-"}};
const scienceRel=id=>ciencias.find(x=>x.relatorioId==id),sciencePen=id=>ciencias.find(x=>x.pendenciaId==id);
$("#entrar").onclick=async()=>{try{$("#loginMsg").textContent="";await signInWithEmailAndPassword(auth,$("#email").value.trim(),$("#senha").value)}catch{$("#loginMsg").textContent="Não foi possível entrar. Verifique e-mail e senha."}};$("#sair").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u){user=null;$("#login").classList.remove("hidden");$("#app").classList.add("hidden");return}user=u;const s=await getDoc(doc(db,"usuarios",u.uid));if(!s.exists()||s.data().ativo!==true){await signOut(auth);return}perfil=s.data();if(!["administrador","gestor"].includes(perfil.perfil)){$("#loginMsg").textContent="Este acesso é exclusivo da gestão.";await signOut(auth);return}$("#userBadge").textContent=`${perfil.nome||"Gestão"} • ${perfil.perfil}`;$("#login").classList.add("hidden");$("#app").classList.remove("hidden");escutar()});
function escutar(){onSnapshot(query(collection(db,"relatorios"),orderBy("createdAt","desc")),s=>{rel=s.docs.map(d=>({id:d.id,...d.data()}));syncRender()});onSnapshot(collection(db,"pendencias"),s=>{pen=s.docs.map(d=>({id:d.id,...d.data()}));syncRender()});onSnapshot(collection(db,"ciencia_gestao"),s=>{ciencias=s.docs.map(d=>({id:d.id,...d.data()}));syncRender()})}
function syncRender(){$("#lastUpdate").textContent=`Sincronizado • ${new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`;renderAll()}
document.querySelectorAll(".nav[data-page]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("on"));b.classList.add("on");document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$("#page-"+b.dataset.page).classList.add("active");renderAll()});
["#dIni","#dFim","#fTurno","#fResp","#rData","#rTurno","#rResp","#rSit","#rBusca","#pStatus","#pTurno","#pBusca"].forEach(id=>$(id).addEventListener("input",renderAll));$("#limpar").onclick=()=>{$("#dIni").value=$("#dFim").value=$("#fTurno").value=$("#fResp").value="";renderAll()};
function dashFilter(r){return(!$("#dIni").value||r.dataTurno>=$("#dIni").value)&&(!$("#dFim").value||r.dataTurno<=$("#dFim").value)&&(!$("#fTurno").value||r.turno==$("#fTurno").value)&&(!$("#fResp").value||r.responsavelNome==$("#fResp").value)}
function relFiltrados(){let q=norm($("#rBusca").value);return rel.filter(r=>(!$("#rData").value||r.dataTurno==$("#rData").value)&&(!$("#rTurno").value||r.turno==$("#rTurno").value)&&(!$("#rResp").value||r.responsavelNome==$("#rResp").value)&&(!$("#rSit").value||norm(r.situacao)==$("#rSit").value)&&(!q||norm(JSON.stringify(r)).includes(q)))}
function renderAll(){let a=rel.filter(dashFilter),n=a.filter(x=>norm(x.situacao)=="NORMAL").length,at=a.filter(x=>norm(x.situacao)=="ATENCAO").length,oc=a.filter(x=>norm(x.situacao)=="OCORRENCIA").length,openPen=pen.filter(x=>["ABERTA","EM ACOMPANHAMENTO"].includes(norm(x.status))).length,semCi=a.filter(x=>!scienceRel(x.id)).length;
$("#kRel").textContent=a.length;$("#kNor").textContent=n;$("#kAte").textContent=at;$("#kOco").textContent=oc;$("#kPen").textContent=openPen;$("#kSci").textContent=semCi;badge("#navScience",rel.filter(x=>!scienceRel(x.id)).length);badge("#navPen",openPen);
let vals=[["Normal",n,"greenFill"],["Atenção",at,"orangeFill"],["Ocorrência",oc,"redFill"],["Total",a.length,"totalFill"]],mx=Math.max(1,...vals.map(x=>x[1]));$("#bars").innerHTML=vals.map(x=>`<div class="barrow"><b>${x[0]}</b><div class="bar"><div class="fill ${x[2]}" style="width:${x[1]/mx*100}%"></div></div><b>${x[1]}</b></div>`).join("");
renderTurnos(a);renderScience(a);renderAttention(a);$("#recentes").innerHTML=a.slice(0,5).map(cardRel).join("")||"<p class='empty'>Nenhum relatório no filtro.</p>";renderSystem(a);renderOper(a);renderTrend(a);renderRel();renderPen();bind()}
function badge(id,n){$(id).textContent=n;$(id).classList.toggle("hidden",!n)}
function renderTurnos(a){const nomes={A:"Daniele",B:"Carina",C:"Natiély",D:"Wanderson"};$("#turnosStatus").innerHTML=["A","B","C","D"].map(t=>{let r=a.find(x=>x.turno==t);if(!r)return`<div class="turnoBox muted"><b>Turno ${t}</b><span>Sem relatório no período</span><small>${nomes[t]}</small></div>`;let s=norm(r.situacao),cl=s=="OCORRENCIA"?"danger":s=="ATENCAO"?"warning":"ok";return`<div class="turnoBox ${cl}"><b>Turno ${t}</b><span>${s}</span><small>${esc(r.responsavelNome||nomes[t])} • ${dataBR(r.dataTurno)}</small></div>`}).join("")}
function renderScience(a){let ok=a.filter(x=>scienceRel(x.id)).length,wait=a.length-ok,pct=a.length?Math.round(ok/a.length*100):0;$("#scienceStats").innerHTML=`<div class="scienceGauge"><strong>${pct}%</strong><span>dos relatórios com ciência</span></div><div class="scienceRows"><div><b>${ok}</b><span>Com ciência</span></div><div><b>${wait}</b><span>Aguardando</span></div></div>`}
function renderAttention(a){let alerts=[];a.forEach(r=>{let s=norm(r.situacao),sf=norm(r.sistemaFadiga),co=norm(r.condicoesOperacionais);if(s=="OCORRENCIA"||s=="ATENCAO"||sf=="INSTAVEL"||sf=="INDISPONIVEL"||co=="CRITICAS"||co=="CRITICA")alerts.push({r,level:s=="OCORRENCIA"||sf=="INDISPONIVEL"||co.startsWith("CRIT")?"red":"orange",txt:s=="OCORRENCIA"?"Ocorrência registrada":sf=="INDISPONIVEL"?"Sistema indisponível":sf=="INSTAVEL"?"Sistema instável":co.startsWith("CRIT")?"Condição operacional crítica":"Turno em atenção"})});pen.filter(p=>["ABERTA","EM ACOMPANHAMENTO"].includes(norm(p.status))).slice(0,4).forEach(p=>alerts.push({p,level:"orange",txt:"Pendência aberta"}));alerts=alerts.slice(0,8);$("#attentionCount").textContent=alerts.length;$("#attentionList").innerHTML=alerts.map(x=>x.r?`<div class="alertLine ${x.level}"><div><b>${x.txt}</b><span>${esc(x.r.responsavelNome)} • Turno ${esc(x.r.turno)} • ${dataBR(x.r.dataTurno)}</span></div><button class="miniView" data-id="${x.r.id}">Ver</button></div>`:`<div class="alertLine ${x.level}"><div><b>${x.txt}</b><span>${esc(x.p.descricao||"-")}</span></div></div>`).join("")||"<div class='allGood'>✓ Nenhum item crítico no filtro atual.</div>"}
function renderSystem(a){let vals=[["Normal",a.filter(x=>norm(x.sistemaFadiga)=="NORMAL").length,"ok"],["Instável",a.filter(x=>norm(x.sistemaFadiga)=="INSTAVEL").length,"warning"],["Indisponível",a.filter(x=>norm(x.sistemaFadiga)=="INDISPONIVEL").length,"danger"]];$("#systemStats").innerHTML=`<div class="miniStats">${vals.map(x=>`<span class="${x[2]}"><b>${x[1]}</b>${x[0]}</span>`).join("")}</div>`}
function renderOper(a){let normal=a.filter(x=>["NORMAIS","NORMAL"].includes(norm(x.condicoesOperacionais))).length,aten=a.filter(x=>norm(x.condicoesOperacionais)=="ATENCAO").length,crit=a.filter(x=>norm(x.condicoesOperacionais).startsWith("CRIT")).length;$("#operStats").innerHTML=`<div class="miniStats"><span class="ok"><b>${normal}</b>Normais</span><span class="warning"><b>${aten}</b>Atenção</span><span class="danger"><b>${crit}</b>Críticas</span></div>`}
function renderTrend(a){let map={};a.forEach(r=>{if(!r.dataTurno)return;map[r.dataTurno]??={total:0,alert:0};map[r.dataTurno].total++;if(["ATENCAO","OCORRENCIA"].includes(norm(r.situacao)))map[r.dataTurno].alert++});let ds=Object.keys(map).sort().slice(-10),mx=Math.max(1,...ds.map(d=>map[d].total));$("#trend").innerHTML=ds.length?`<div class="trendBars">${ds.map(d=>`<div class="trendCol"><div class="trendTrack"><div class="trendTotal" style="height:${Math.max(8,map[d].total/mx*100)}%"></div><div class="trendAlert" style="height:${map[d].alert?Math.max(8,map[d].alert/mx*100):0}%"></div></div><b>${map[d].total}</b><span>${dataBR(d).slice(0,5)}</span></div>`).join("")}</div><div class="trendLegend"><span>■ Total de relatórios</span><span>■ Atenções/Ocorrências</span></div>`:"<p class='empty'>Sem dados suficientes para tendência.</p>"}
function cardRel(r){let s=norm(r.situacao),c=s=="OCORRENCIA"?"red":s=="NORMAL"?"green":"",ci=scienceRel(r.id);return`<div class="item ${c}"><span class="tag ${c}">${s||"-"}</span><h3>${esc(r.responsavelNome)} • Turno ${esc(r.turno)}</h3><div class="meta">${dataBR(r.dataTurno)} • ${esc(r.horario)}</div><p>${esc(r.resumo||"Sem resumo")}</p>${ci?`<div class="science">✓ Ciência: ${esc(ci.gestorNome)} • ${tsBR(ci.createdAt)}</div>`:`<div class="awaitScience">◷ Aguardando ciência da gestão</div>`}<button class="action view" data-id="${r.id}">Visualizar completo</button></div>`}
function renderRel(){let a=relFiltrados();$("#listaRel").innerHTML=a.map(cardRel).join("")||"<p class='empty'>Nenhum relatório encontrado.</p>"}
function renderPen(){let q=norm($("#pBusca").value),a=pen.filter(p=>(!$("#pStatus").value||norm(p.status)==$("#pStatus").value)&&(!$("#pTurno").value||p.turnoOrigem==$("#pTurno").value)&&(!q||norm(JSON.stringify(p)).includes(q)));$("#listaPen").innerHTML=a.map(p=>{let ci=sciencePen(p.id),st=norm(p.status)||"ABERTA",acoes="";if(st==="ABERTA")acoes=`<button class="action acompanharPen" data-id="${p.id}">◷ Colocar em acompanhamento</button><button class="action tratarPen secondaryAction" data-id="${p.id}">✓ Marcar como tratada</button>`;else if(st==="EM ACOMPANHAMENTO")acoes=`<button class="action tratarPen" data-id="${p.id}">✓ Marcar como tratada</button><button class="action reabrirPen secondaryAction" data-id="${p.id}">↶ Voltar para aberta</button>`;else if(st==="TRATADA")acoes=`<button class="action reabrirPen secondaryAction" data-id="${p.id}">↶ Reabrir pendência</button>`;return`<div class="item"><span class="tag status-${st.replaceAll(" ","-")}">${st}</span><h3>Pendência</h3><div class="meta">Origem: ${esc(p.openedByNome||"-")} • Turno ${esc(p.turnoOrigem||"-")} • Abertura: ${tsBR(p.openedAt)}</div><p>${esc(p.descricao||"-")}</p>${ci?`<div class="science">✓ Ciência da gestão: ${esc(ci.gestorNome)} • ${tsBR(ci.createdAt)}</div>`:`<div class="awaitScience">◷ Aguardando ciência da gestão</div><button class="action sciencePen" data-id="${p.id}">✓ Dar ciência</button>`}<div class="pendingActions">${acoes}</div></div>`}).join("")||"<p class='empty'>Nenhuma pendência encontrada.</p>"}
function bind(){document.querySelectorAll(".view,.miniView").forEach(b=>b.onclick=()=>abrir(rel.find(x=>x.id==b.dataset.id)));document.querySelectorAll(".sciencePen").forEach(b=>b.onclick=()=>darCienciaPendencia(b.dataset.id));document.querySelectorAll(".acompanharPen").forEach(b=>b.onclick=()=>mudarStatusPendencia(b.dataset.id,"EM ACOMPANHAMENTO"));document.querySelectorAll(".tratarPen").forEach(b=>b.onclick=()=>mudarStatusPendencia(b.dataset.id,"TRATADA"));document.querySelectorAll(".reabrirPen").forEach(b=>b.onclick=()=>mudarStatusPendencia(b.dataset.id,"ABERTA"))}
function det(a,b,help=""){return`<div class="detail"><b>${a}</b>${help?`<small>${help}</small>`:""}<br>${esc(b||"-")}</div>`}
function abrir(r){if(!r)return;relAtual=r;let ci=scienceRel(r.id);$("#modalBody").innerHTML=`<div class="eyebrow">RELATÓRIO COMPLETO</div><h1>${esc(r.responsavelNome)} • Turno ${esc(r.turno)}</h1>${det("Data",dataBR(r.dataTurno),"Data operacional informada no relatório.")}${det("Horário",r.horario,"Faixa de horário correspondente ao turno.")}${det("Situação",r.situacao,"Classificação geral do turno: Normal, Atenção ou Ocorrência.")}${det("Sistema de Fadiga",r.sistemaFadiga,"Condição de funcionamento do sistema durante o turno.")}${det("Condições Operacionais",r.condicoesOperacionais,"Condição operacional observada pela equipe.")}${det("Resumo",r.resumo,"Síntese das principais informações do turno.")}${det("Ocorrências",r.ocorrencias,"Eventos relevantes registrados durante o turno.")}${det("Pendências recebidas",r.pendenciasRecebidas,"Itens recebidos do turno anterior.")}${det("Pendências geradas",r.pendenciasGeradas,"Itens deixados para acompanhamento do próximo turno.")}${det("Ações realizadas",r.acoes,"Providências adotadas durante o turno.")}${det("Passagem de turno / Observações",r.passagemTurno,"Orientações e informações importantes para continuidade.")}${ci?`<div class="science big">✓ CIÊNCIA DA GESTÃO<br>${esc(ci.gestorNome)} • ${tsBR(ci.createdAt)}</div>`:""}`;$("#btnCiencia").style.display=ci?"none":"inline-block";$("#modal").classList.remove("hidden")}
$("#fechar").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target.id=="modal")$("#modal").classList.add("hidden")};
$("#btnCiencia").onclick=async()=>{if(!relAtual||!user)return;if(!confirm("Registrar ciência da gestão neste relatório?"))return;await addDoc(collection(db,"ciencia_gestao"),{relatorioId:relAtual.id,gestorUid:user.uid,gestorNome:perfil.nome||"Gestão",tipo:"RELATORIO",createdAt:serverTimestamp()});abrir(relAtual)};
async function darCienciaPendencia(id){if(!confirm("Registrar ciência da gestão nesta pendência? A ciência não encerra a pendência."))return;await addDoc(collection(db,"ciencia_gestao"),{pendenciaId:id,gestorUid:user.uid,gestorNome:perfil.nome||"Gestão",tipo:"PENDENCIA",createdAt:serverTimestamp()})}
async function mudarStatusPendencia(id,status){let msg=status==="TRATADA"?"Confirmar que esta pendência foi tratada?":status==="EM ACOMPANHAMENTO"?"Colocar esta pendência em acompanhamento?":"Reabrir esta pendência?";if(!confirm(msg))return;await updateDoc(doc(db,"pendencias",id),{status,statusAtualizadoEm:serverTimestamp(),statusAtualizadoPorUid:user.uid,statusAtualizadoPorNome:perfil.nome||"Gestão"})}
$("#btnPrint").onclick=()=>window.print();$("#imprimirLista").onclick=()=>window.print();$("#imprimirDash").onclick=()=>window.print();
function excelRows(a){return a.map(r=>({"Data":dataBR(r.dataTurno),"Turno":r.turno,"Horário":r.horario,"Colaborador":r.responsavelNome,"Situação":r.situacao,"Sistema de Fadiga":r.sistemaFadiga,"Condições Operacionais":r.condicoesOperacionais,"Resumo":r.resumo,"Ocorrências":r.ocorrencias,"Pendências Recebidas":r.pendenciasRecebidas,"Pendências Geradas":r.pendenciasGeradas,"Ações Realizadas":r.acoes,"Passagem de Turno / Observações":r.passagemTurno,"Ciência da Gestão":scienceRel(r.id)?"SIM":"NÃO"}))}
$("#exportarExcel").onclick=()=>{let a=relFiltrados();if(!a.length){alert("Nenhum relatório para exportar.");return}let ws=XLSX.utils.json_to_sheet(excelRows(a)),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Relatórios");XLSX.writeFile(wb,`Relatorios_Fadiga_${new Date().toISOString().slice(0,10)}.xlsx`)};
$("#exportarResumo").onclick=()=>{let a=rel.filter(dashFilter);if(!a.length){alert("Nenhum relatório no período para exportar.");return}let resumo=[{"Indicador":"Relatórios","Quantidade":a.length},{"Indicador":"Normais","Quantidade":a.filter(x=>norm(x.situacao)=="NORMAL").length},{"Indicador":"Atenções","Quantidade":a.filter(x=>norm(x.situacao)=="ATENCAO").length},{"Indicador":"Ocorrências","Quantidade":a.filter(x=>norm(x.situacao)=="OCORRENCIA").length},{"Indicador":"Aguardando ciência","Quantidade":a.filter(x=>!scienceRel(x.id)).length},{"Indicador":"Pendências abertas/em acompanhamento (geral)","Quantidade":pen.filter(x=>["ABERTA","EM ACOMPANHAMENTO"].includes(norm(x.status))).length}];let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(resumo),"Resumo Gerencial");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(excelRows(a)),"Relatórios do Período");XLSX.writeFile(wb,`Resumo_Gerencial_Fadiga_${new Date().toISOString().slice(0,10)}.xlsx`)};
